In [ ]:
print('hello al')

In [1]:
import numpy as np
a = np.random.randint(1,100, size=(10,5))
a

array([[67, 60, 90, 77, 86],
       [ 9, 70, 59, 16,  8],
       [ 3, 19, 49, 56,  9],
       [33, 75, 65, 37, 61],
       [ 7, 14, 68,  5, 94],
       [87, 30, 74, 47, 78],
       [23, 55, 90, 87, 51],
       [17, 76, 15, 74, 49],
       [26, 72, 19, 30, 33],
       [79, 15, 85, 24, 16]])

In [2]:
b = np.random.randint(10,20,size = 10)
b

array([12, 10, 16, 13, 14, 10, 10, 10, 12, 16])

In [5]:
a.T.dot(b)

array([4315, 5609, 7629, 5355, 5797])